# -*- coding: utf-8 -*-
"""Event Website - Scraped and generated Data from it.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tIZa9243NlNKyCPf65xRrn048Buvr5k

## Importing libraries
"""

import requests

from bs4 import BeautifulSoup as bs

"""#### Data link Assigning to variables so that we can fetch easily"""

birth_equ = "https://www.bookmyballoons.in/product-category/"+"birthday-decoration"

wed_equ = "https://www.bookmyballoons.in/product-category/"+"wedding-decoration"

baby_equ = "https://www.bookmyballoons.in/services/"+"baby-shower-decoration-in-bangalore"

baby_deq = "https://www.bookmyballoons.in/services/"+"welcome-baby-decoration-in-bangalore"

bach_party = "https://www.bookmyballoons.in/services/"+"bachelor-party-decoration-in-bangalore"

party_list = [birth_equ,wed_equ,baby_equ,baby_deq,bach_party]

requests.get(party_list[4])

party_list

# Used URLlib and urlopen for simple interface

from urllib.request import urlopen

part1 = urlopen(party_list[0])
part2 = part1.read()

data1 = bs(part2,'html.parser')

part1 = urlopen(party_list[1])
part2 = part1.read()

data2 = bs(part2,'html.parser')

part1 = urlopen(party_list[2])
part2 = part1.read()

data3 = bs(part2,'html.parser')

part1 = urlopen(party_list[3])
part2 = part1.read()

data4 = bs(part2,'html.parser')

part1 = urlopen(party_list[4])
part2 = part1.read()

data5 = bs(part2,'html.parser')



party_list[4]

data1

find_data1 = data1.find_all("div", {"class":"woo-buttons-on-img"})

len(find_data1)

event_image = find_data1[0].img["data-src"]

event_names =find_data1[1].img['alt']
event_links =find_data1[1].a['href']

event_image_list = []
event_names_list = []
event_links_list = []

for i in range(0,len(find_data1)):
  event_image = find_data1[i].img["data-src"]
  event_names = find_data1[i].img['alt']
  event_links = find_data1[i].a['href']

  event_image_list.append(event_image)
  event_names_list.append(event_names)
  event_links_list.append(event_links)

print(event_image_list)
print(event_names_list)
print(event_links_list)

print(party_list[0])

find_data1 = data1.find_all("div", {"class":"woo-buttons-on-img"})
len(find_data1)

print("Birthday-Decoration")
print(party_list[0],"\n")

for i in range(len(find_data)):
  print(event_image_list[i])
  print(event_names_list[i])
  print(event_links_list[i],"\n")

find_data2 = data2.find_all("div", {"class":"woo-buttons-on-img"})
len(find_data2)

event_image_list1 = []
event_names_list1 = []
event_links_list1 = []

for i in range(0,len(find_data2)):
  event_image = find_data2[i].img["data-src"]
  event_names = find_data2[i].img['alt']
  event_links = find_data2[i].a['href']

  event_image_list1.append(event_image)
  event_names_list1.append(event_names)
  event_links_list1.append(event_links)

find_data3 = data3.find_all("div", {"class":"woo-buttons-on-img"})
len(find_data3)

event_image_list2 = []
event_names_list2 = []
event_links_list2 = []

for i in range(0,len(find_data3)):
  event_image = find_data3[i].img["data-src"]
  event_names = find_data3[i].img['alt']
  event_links = find_data3[i].a['href']

  event_image_list2.append(event_image)
  event_names_list2.append(event_names)
  event_links_list2.append(event_links)

find_data4 = data4.find_all("div", {"class":"woo-buttons-on-img"})
len(find_data4)

event_image_list3 = []
event_names_list3 = []
event_links_list3 = []

for i in range(0,len(find_data4)):
  event_image = find_data4[i].img["data-src"]
  event_names = find_data4[i].img['alt']
  event_links = find_data4[i].a['href']

  event_image_list3.append(event_image)
  event_names_list3.append(event_names)
  event_links_list3.append(event_links)

find_data5 = data5.find_all("div", {"class":"woo-buttons-on-img"})
len(find_data5)

event_image_list4 = []
event_names_list4 = []
event_links_list4 = []

for i in range(0,len(find_data5)):
  event_image = find_data5[i].img["data-src"]
  event_names = find_data5[i].img['alt']
  event_links = find_data5[i].a['href']

  event_image_list4.append(event_image)
  event_names_list4.append(event_names)
  event_links_list4.append(event_links)

import pandas as pd

data = {

    'Event Name': event_names_list + event_names_list1 + event_names_list2 + event_names_list3 + event_names_list4,
    'Event Image': event_image_list + event_image_list1 + event_image_list2 + event_image_list3 + event_image_list4,
    'Event Link': event_links_list + event_links_list1 + event_links_list2 + event_links_list3 + event_links_list4
}

df = pd.DataFrame(data)

df.to_excel('event_data.xlsx', index=False)
from google.colab import files
files.download('event_data.xlsx')







